web:
  build: cloudpebble/
  ports:
    - "80:80"
  volumes:
    - "./cloudpebble/:/code"
  links:
    - redis
    - postgres
    - s3
    - qemu
    - ycmd
  environment:
    - DEBUG="yes"
    - RUN_WEB="yes"
    - AWS_ENABLED="yes"
    - PORT=80
    # On MAC - go to your settings -> Network -> copy IP address
    # NOTE: you can NOT use 127.0.0.1 or 0.0.0.0 because it will be the machine's IP address, not your PC's address
    - AWS_S3_FAKE_S3=${LOCAL_IP}:8003
    - MEDIA_URL=http://${LOCAL_IP}:8003/builds.cloudpebble.net/
    - QEMU_URLS=http://${LOCAL_IP}:8001/
    - YCM_URLS=http://${LOCAL_IP}:8002/
    - PUBLIC_URL=http://${LOCAL_IP}/
    - LIBPEBBLE_PROXY=wss://cloudpebble-ws.herokuapp.com/tool
    - PEBBLE_AUTH_URL=https://auth.rebble.io
    - GITHUB_ID=${GITHUB_ID}
    - GITHUB_SECRET=${GITHUB_SECRET}
celery:
  build: cloudpebble/
  volumes:
    - "./cloudpebble/:/code"
  links:
    - redis
    - postgres
    - s3
  environment:
    - DEBUG="yes"
    - RUN_CELERY="yes"
    - AWS_ENABLED=yes
    - EXPORT_ROOT=http://${LOCAL_IP}:8003/export.cloudpebble.net/
    - AWS_S3_FAKE_S3=${LOCAL_IP}:8003
qemu:
  build: cloudpebble-qemu-controller/
  volumes:
    - "./cloudpebble-qemu-controller/:/code"
  ports:
    - "8001:80"
ycmd:
  build: cloudpebble-ycmd-proxy/
  volumes:
    - "./cloudpebble-ycmd-proxy/:/code"
  ports:
    - "8002:80"
redis:
  image: redis
postgres:
  volumes:
    - "./pgdata:/var/lib/postgresql/data:rw"
  image: postgres:10.5
s3:
  image: kuracloud/fake-s3
  volumes:
    - "./fake_s3_root:/fakes3_root:rw"
  ports:
    - "8003:4569"
